cmd/watchdogs/main.go
cmd/watchdogs/main_test.go

Travis CI and Circle CI fail with pull request build from forked
repositories because we cannot encrypted environment variables in the
build from forked repositories.

Do not exit 1 with empty WATCHDOGS_GITHUB_API_TOKEN

---

cmd/reviewdog/main.go

use "golang.org/x/net/context" for now to make reviewdog buildable in pre go 1.7

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go
comment.go
comment_iowriter.go
comment_iowriter_test.go
comment_test.go
github.go
github_test.go
reviewdog.go
reviewdog_test.go

Refactor comment writer

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go

* vendoring with git submodule [#57](https://github.com/haya14busa/reviewdog/pull/57) ([haya14busa](https://github.com/haya14busa))
* Improve CI [#64](https://github.com/haya14busa/reviewdog/pull/64) ([haya14busa](https://github.com/haya14busa))
* Introduce GitHub pull reviews api [#63](https://github.com/haya14busa/reviewdog/pull/63) ([haya14busa](https://github.com/haya14busa))
* introduce go-simple [#62](https://github.com/haya14busa/reviewdog/pull/62) ([haya14busa](https://github.com/haya14busa))
* Use os.Unsetenv() instead of os.Setenv(key, "") [#61](https://github.com/haya14busa/reviewdog/pull/61) ([haya14busa](https://github.com/haya14busa))

Bump up version to 0.9.4

---

cmd/reviewdog/main.go

hi.
revewdog is amazing product.
I want using in office.
but reviewdog not working, because my office network in under proxy.
please, use environment proxy setting (http.ProxyFromEnvironment)  like the http.DefaultClient.

using environment proxy setting.

---

cmd/reviewdog/main.go

I think it's better to add the command prefix for error messages so that we can tell where the error messages come from.

Add command name prefix to error message

---

cmd/reviewdog/main.go

The update of https://github.com/google/go-github/pull/692 doesn't allow to use GitHub API Base URL without trailing slash.
```
$ go get -u github.com/haya14busa/reviewdog/cmd/reviewdog
$ reviewdog -ci="circle-ci"
$ reviewdog: fail to run reviewdog: fail to get diff: BaseURL must have a trailing slash, but "https://api.github.com" does not
```

add trailing slash to GitHub default BaseURL

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go

Since Drone.IO have `DRONE_REPO_OWNER` and `DRONE_REPO_NAME` env variables we should use it to identify GH repo instead of split `DRONE_REPO` string.
Refs http://docs.drone.io/environment-reference/

Improve repo name/owner in drone.io

---

cmd/reviewdog/main.go

It doesn't work in CircleCI 2.0.
```
this is not PullRequest build. CI: circle-ci
```
It seems that `CI_PULL_REQUEST` has been renamed to `CIRCLE_PULL_REQUEST`.
https://circleci.com/docs/2.0/env-vars/#build-details
> CI_PULL_REQUEST
> 
> Same as CIRCLE_PULL_REQUEST, only kept for the backward compatibility with 1.0.

support CircleCI 2.0

---

README.md

Hello.
Note that currently, [defaultGithub](https://github.com/haya14busa/reviewdog/blob/master/cmd/reviewdog/main.go#L279) is `https://api.github.com/`.
Therefore `GITHUB_API` must be the same. (end with `/`')

Fix GITHUB_API endpoint

---

README.md
cienv/cienv.go
cienv/cienv_test.go
cmd/reviewdog/doghouse.go
doghouse/service.go

Check Run need branch data and doghouse can get branch data via GitHub
Pull Request API, but if branch data is available in doghouse check request,
we can reduce one GitHub API call.

doghouse: add branch field

---

cmd/reviewdog/main.go
gitlab_mr_commit.go
gitlab_mr_commit_test.go
gitlab_mr_diff.go
gitlab_mr_diff_test.go

We can use GitLabMergeRequestDiff service both for GitLabMergeRequestCommitCommenter and 
new commenter with discussion API https://github.com/haya14busa/reviewdog/issues/157

gitlab: add GitLabMergeRequestDiff service separately

---

cmd/reviewdog/doghouse.go

```
"reviewdog: this is not PullRequest build"
+ "\n"
```

add newline to tail of message.

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go
filter.go
service/github/github.go
service/gitlab/gitlab_mr_commit.go

Use filepath.ToSlash for local paths
```
ok  	github.com/reviewdog/reviewdog	(cached)
ok  	github.com/reviewdog/reviewdog/cienv	(cached)
ok  	github.com/reviewdog/reviewdog/cmd/reviewdog	(cached)
ok  	github.com/reviewdog/reviewdog/diff	(cached)
?   	github.com/reviewdog/reviewdog/doghouse	[no test files]
?   	github.com/reviewdog/reviewdog/doghouse/appengine	[no test files]
?   	github.com/reviewdog/reviewdog/doghouse/appengine/statik	[no test files]
ok  	github.com/reviewdog/reviewdog/doghouse/client	(cached)
ok  	github.com/reviewdog/reviewdog/doghouse/server	(cached)
ok  	github.com/reviewdog/reviewdog/doghouse/server/ciutil	(cached)
ok  	github.com/reviewdog/reviewdog/doghouse/server/cookieman	(cached)
?   	github.com/reviewdog/reviewdog/doghouse/server/storage	[no test files]
ok …
```

Fixes Windows related issues

---

.travis.yml

workaround for https://github.com/reviewdog/reviewdog/pull/222#issuecomment-501131351
> https://travis-ci.org/reviewdog/reviewdog/jobs/544561733
> 
> installing honnef.co/go/tools/cmd/gosimple is failing. :(
> 
> ```
> $ go get honnef.co/go/tools/cmd/gosimple
> go: finding honnef.co/go/tools/cmd/gosimple latest
> go: finding honnef.co/go/tools latest
> go: downloading honnef.co/go/tools v0.0.0-20190607181801-497c8f037f5a
> go: extracting honnef.co/go/tools v0.0.0-20190607181801-497c8f037f5a
> go get honnef.co/go/tools/cmd/gosimple: module honnef.co/go/tools@latest (v0.0.0-20190607181801-497c8f037f5a) found, but does not contain package honnef.co/go/tools/cmd/gosimple
> The command "go get honnef.co/go/tools/cmd/gosimple" failed and exited with 1 during .
> ```

workaround for failing honnef.co/go/tools install

---

.gitignore
package-lock.json
package.json

`package.json` has the dependencies information,
but has no imformation for the dependencies of dependencies.
So the `node_modules` tree may differ between the environments
such as local and CI.
We should manage the `package-lock.json` to prevent it.
See https://docs.npmjs.com/files/package-lock.json

lock the version of npm packages

---

cmd/reviewdog/main.go
doghouse/appengine/github.go
doghouse/appengine/github_webhook.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/server/github.go
doghouse/server/github_checker.go
go.mod
go.sum
service/github/github.go
service/github/github_test.go

google/go-github was upgraded to v28 in #259, however due to semantic
import versioning, you continued consuming v27. All import statements
are now migrated to /v27/, and no breakage occurred.
The pseudo-version declared for the reviewdog/errorformat module had an
incorrect timestamp. This is a fatal issue in go1.13, see release notes,
thus that too is fixed.
Since this module builds successfully with go1.13, I have upgraded the
go directive.

fixup go.mod and go-github usage

---

README.md
cmd/reviewdog/main.go

Hi there!
Some CI-services don't provide information such as Pull Request ID. So, I decided to get Pull Request ID by branch name or commit hash.

Get Pull Request ID by branch name or commit hash

---

.gitlab-ci.yml

because it cannot create MergeRequest to master itself.

Do not run GitLab CI for master branch

---

doghouse/server/doghouse.go
doghouse/server/doghouse_test.go

I remove `BlobHRef` from struct of github.CheckRunAnnotation.
Because removed variable  in `go-github` repo. So I think It would be better to remove in this repo too.
FYI : https://github.com/google/go-github/pull/1242

Remove BlobHRef from struct of github.CheckRunAnnotation

---

doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/server/github_checker.go
doghouse/service.go

It seems it's not required anymore and it's not referred from the
document. https://developer.github.com/v3/checks/runs/#create-a-check-run

Do not set CreateCheckRunOptions.HeadBranch

---

doghouse/server/github.go
go.mod
go.sum

It appears that the old version of ghinstallation was breaking the go get installation. Updated the version to the latest one and fixed the compilation errors.
See https://github.com/bradleyfalzon/ghinstallation/releases/tag/v1.0.0

fixes #359

---

cmd/reviewdog/doghouse.go
cmd/reviewdog/doghouse_test.go
cmd/reviewdog/main.go
doghouse/server/doghouse.go
doghouse/service.go
filter.go
filter_test.go
project/run.go
project/run_test.go
reviewdog.go
reviewdog_test.go

Current behaviour:
When reviewdog filters the check results by diff, which is either provided by cli option or taken from Gitbub or Gitlab PR/MR, it does so only taking into account the lines marked as added in the diff. This has certain downsides described in #187.
New behaviour:
Filter check results by all the lines from diff but add the option to force the existing logic of filtering only by added diff lines.

Filter check results by all lines from diff by default

---

README.md

go tool vet itself and `-shadowstrict` option are not supported in newer Go
reference: https://golang.org/doc/go1.12#vet

go tool vet and shadow option are not available

---

go.sum
project/run.go
project/run_test.go
resultmap.go

If a tool fails and reviewdog **cannot** capture any findings, the tool
should have been failed unexpectedly, so reviewdog will also exit with 1.
If a tool failes and reviewdog **can** capture at least one finding,
reviewdog exit with 0 because most linters exit 1 if it finds errors.
related: #446

[ProjectRun] exit 1 if a tool fails with zero-findings

---

cienv/cienv.go

GitLab has a Feature called Merge Trains(see https://docs.gitlab.com/ee/ci/merge_request_pipelines/pipelines_for_merged_results/merge_trains/), which creates a "speculative" merge commit of the branch with the merge target and runs CI on that commit.
This commit is not part of the Merge Request, therefore the logic to find the MR for the SHA that works without Merge Trains does not work any more.
Thankfully the env var "CI_MERGE_REQUEST_IID" is provided to get the MR for the pipeline (see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html).

fix: GitLab CI MergeTrains

---

cmd/reviewdog/doghouse.go

If you create your own app integration and use that to create your GitHub API key, you can use that key to push to the checks API without being in GitHub actions. This works fine, there's just no way to skip the doghouse server without also failing other github action conditionals.

Allow forced skipping of the doghouse server.

---

.github/workflows/reviewdog.yml
.gitlab-ci.yml
difffilter/filter.go
difffilter/filter_test.go
filter.go
filter_test.go
reviewdog.go
service/commentutil/commentutil.go
service/gitlab/gitlab_mr_discussion.go
service/gitlab/gitlab_mr_discussion_test.go

GitLab returns an error if old path/line is not specified where
appropriate.

gitlab: support -filter-mode=[file/diff_context]

---

CHANGELOG.md
README.md
cmd/reviewdog/main.go

This should be a simple change, although it has not been extensively tested.
Closes #563.

cmd: use CI_API_V4_URL env as gitlab API URL

---

CHANGELOG.md
README.md

Users need to use --filter-mode=nofilter to report results outside diff
ref: #637

github-check doesn't report results outside diff by default now

---

CHANGELOG.md
cienv/github_actions.go
cmd/reviewdog/doghouse.go
cmd/reviewdog/main.go
go.sum

Head and base repos can be the same *forked* repo, so refering to head
repo's "fork" field was not enough.
Fix #603

Fix detection logic to determin Pull Requests from forked repo

---

.github/goreleaser-header.md
.github/workflows/release.yml

It seems process substitution syntax did not work because 'args' for
actions won't be handled as bash arguments.
Error:
/opt/hostedtoolcache/goreleaser-action/0.138.0/x64/goreleaser release
--rm-dist --release-header <(echo -n 'See
[CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md)')
⨯ command failed            error=unknown shorthand flag: 'n' in -n
https://github.com/reviewdog/reviewdog/runs/819469712?check_suite_focus=true

Fix v0.10.1 release

---

cmd/reviewdog/main.go
parser.go
parser_test.go

Support rdjsonl as input format

---

doghouse/appengine/checker.go
doghouse/appengine/main.go

// The provided tr http.RoundTripper should be shared between multiple
// installations to ensure reuse of underlying TCP connections.
https://github.com/bradleyfalzon/ghinstallation/blob/81f7095e75089d688962bb75ba9814748d90f004/transport.go#L72-L73

doghouse: Use shared http.RoundTripper

---

_testdata/custom_rdjsonl.json
parser.go
parser_test.go

protojson: https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson
It supports unmarshaling ENUM both by number and enum name.

Use protojson to unmarshal rdjsonl 

---

service/github/github.go
service/github/github_test.go

It actually should use the end line as-is. For example, if a suggestion
want to remove line-break, the end line actually needs to be the line after
the line-break.

github-pr-review: fix rnd position with column == 1 handling

---

comment_iowriter.go
comment_iowriter_test.go
reviewdog.go
service/commentutil/commentutil.go
service/gerrit/change_review.go
service/gerrit/change_review_test.go
service/github/github_test.go
service/gitlab/gitlab_mr_commit_test.go
service/gitlab/gitlab_mr_discussion_test.go

It's actually needless and each reporter should format the comment body.

Remove reviewdog.Comment.Body

---

CHANGELOG.md

Bump version to v0.11.0

---

README.md

I guess `git diff FETCH_HEAD` works for most cases for local runs
regardless of the branch name (master/main).

Use FETCH_HEAD as an example of git diff command

---

CHANGELOG.md
cienv/github_actions.go
cmd/reviewdog/doghouse.go
cmd/reviewdog/main.go

Related to #706,  #759
This PR just allows the `pull_request_target` trigger even if it's from a forked repo. GITHUB_TOKEN via the trigger has enough read/write permission to call review APIs.

Allow GitHub PR reporting for a forked repository iff it's triggered by pull_request_target

---

.github/workflows/codeql-analysis.yml

> 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
e.g. https://github.com/reviewdog/reviewdog/actions/runs/699431209
ref. https://docs.github.com/en/code-security/secure-coding/troubleshooting-the-codeql-workflow#warning-git-checkout-head2-is-no-longer-necessary

fix a warning of CodeQL Analysis

---

CHANGELOG.md
cmd/reviewdog/main.go

This PR make reviewdog treat `GITHUB_API_URL` environment variable as the same as `GITHUB_API`
Close: #975 
related: reviewdog/action-tflint#38, reviewdog/action-golangci-lint#81

treat GITHUB_API_URL env as same as GITHUB_API env

---

.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml
go.mod
scripts/trigger-depup/go.mod

According to [Go Release Policy](https://golang.org/doc/devel/release#policy), Go v1.14 has been already unsupported.
We should update the latest version of Go, Go v1.16

Bump Go 1.16

---

.github/workflows/release.yml

goreleaser warns darwin/arm64 will skip because goreleaser can't find Go 1.16.
https://github.com/reviewdog/reviewdog/runs/2956075029?check_suite_focus=true#step:7:22
> ```
>       • building binaries
>          • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
> ```
We need to setup Go 1.16 during not only building but also checking.

setup Go when we run goreleaser check

---

README.md

using `go get` for installing commands will be deprecated.
we should use `go install` instead of it.
> https://tip.golang.org/doc/go1.17#go-get
> go get prints a deprecation warning when installing commands outside the main module (without the -d flag).
> go install cmd@version should be used instead to install a command at a specific version, using a suffix like @latest or @v1.2.3.
> In Go 1.18, the -d flag will always be enabled, and go get will only be used to change dependencies in go.mod.

use `go install` instead of `go get`

---

CHANGELOG.md
cienv/bitbucket_pipelines.go
cmd/reviewdog/main.go
service/bitbucket/bitbucket.go

Added support for Bitbucket pipes (equivalent of GitHub Actions).
Ran into a few problems trying to get this running, and confirmed with the Bitbucket team that I needed to be using the docker proxy when running within a pipe.
In regards to the environment variable `BITBUCKET_PIPE_STORAGE_DIR` I have also confirmed with the pipelines team that this is a valid environment variable to check against, at least until they add a more explicit env var to check against.

Added support for Bitbucket Pipes within Pipelines

---

cienv/github_actions.go

this should fix #1010
I don't know why `action_name` is removed from the `GITHUB_EVENT_PATH`, but it's documented as env `GITHUB_EVENT_NAME` now
And sorry, I'm new here, could anyone help me with the changelog? How should I add this.

fix(github): detect pr_target

---

CHANGELOG.md
service/commentutil/code_fence.go
service/commentutil/code_fence_test.go
service/github/github.go
service/github/github_test.go

When reviewdog suggests the following code
> ```
> original code
> ```
modified as
> ````
> reviewdog suggestion
> ```
> some code
> ```
> ````
the suggestion comment should be
> ````diff 
> -original code
> +reviewdog suggestion
> +```
> +some code
> +```
> ````
but actually, reviewdog suggests the following comment:
> ```diff
> -original code
> +reviewdog suggestion
> ```
> some code
> ```
> ```
This is because the markdown parser creates wrong pairs of code fences.
> ````markdown
> ```suggestion 
> reviewdog suggestion
> ```
> some code
> ```
> ```
> ````
The document of GitHub markdown says that it is needed to wrap them inside quadruple backticks in this case.
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fen …

Fix suggestion includes fenced code blocks

---

.github/workflows/codeql-analysis.yml
.github/workflows/deploy-doghouse.yml
.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml

This PR adds specific permissions to the existing workflows under .github/workflows.
GitHub provides a [feature](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) to set permissions for the GITHUB_TOKEN. I have implemented a [GitHub App](https://github.com/apps/step-security) to automatically calculate the right permissions for a given workflow.  
I am trying the App out on public repositories, by forking them, installing the App on the fork, and manually creating PRs with the fixed workflows.  
I have manually reviewed the changes, and they do look good to me. If something looks off, please let me know. Please try it out on other repos and share your feedback. Thanks!

Add specific permissions to workflows under .github/workflows

---

README.md

Hi there,
first of all I really want to spend some words to thank @haya14busa and all the reviewdog contributors for bringing such a powerful and useful code review tool to the dev community. What staggers me the most is its ease of use and the large and growing number of supported code quality tools, linters etc. Keep going! 🚀 
While looking at the built-in error formats I noticed tsc was supported by reviewdog, but no GitHub Action was available for it...so I built one. :)
The action is available [here](https://github.com/EPMatt/reviewdog-action-tsc). If you have any suggestion or improvement, I'd be happy to hear your opinion. :)
This PR just adds a link to the action's repository to the list of public reviewdog GitHub Actions, provided in the README file.
Thank you!

GitHub Action for TypeScript Compiler (tsc)

---

cmd/reviewdog/doghouse_test.go
cmd/reviewdog/main.go
cmd/reviewdog/main_test.go
diff_test.go
doghouse/appengine/github.go
doghouse/appengine/main.go
doghouse/client/client.go
doghouse/server/github_checker.go
parser/rdjson.go
service/bitbucket/cloud_api_client.go
service/bitbucket/server_api_client.go

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

refactor: move from io/ioutil to io and os packages

---

README.md

Just noticed https://github.com/reviewdog/action-black was missing from the list, whilst making some PRs over there.

Add action-black to public plugins

---

CHANGELOG.md

The latest release v0.13.0 is released almost a half year ago.
Let's release a new version.

update changelog for releasing v0.13.1

---

CHANGELOG.md

Bump version: support end line/column errorformat

---

README.md

Hi there!
This PR adds a link for the [reviewdog/action-shfmt](https://github.com/reviewdog/action-shfmt) to the list of available GitHub Actions in the README, under the _Shell Script_ section. 🚀

shfmt Github Action - add link to README

---

README.md

This looks like it was a copy-paste error. The link for action-pylint correctly points to pylint, but the link text says "pyright".

Fix typo - action-pylint runs pylint, not pyright

---

.circleci/config.yml
.github/workflows/reviewdog.yml
.gitlab-ci.yml
linters/README.md
linters/go.mod

Error: /bin/bash: line 135: golint: command not found

Fix the GitLab CI

---

CHANGELOG.md
service/bitbucket/cloud_api_client.go
service/bitbucket/server_api_client.go
service/bitbucket/server_api_context.go
service/bitbucket/server_api_context_test.go

Fix the parsing of BITBUCKET_SERVER_URL with subpath #1124
- Fix the parsing by including the path into client configuration
- Add test cases for the parsing
- Fix typos in error messages
-  Distinguish between Bitbucket Cloud and Bitbucket Server for API errors

Allow BITBUCKET_SERVER_URL to have subpath

---

README.md

Hi! Thank you for a pretty code review tool 🐶
Inspired by this great tool, I just built and published a missing GitHub Action for [rails_best_practices](https://github.com/flyerhzm/rails_best_practices).
<https://github.com/blooper05/action-rails_best_practices>
This PR just adds a link to the action's repository to the list of public reviewdog GitHub Actions, provided in the README.
I for one would be happy if this could contribute in any way to the enrichment of reviewdog ecosystem.
Please check my changes and merge them if you like it. Thanks!
---

docs(readme): Add a link to action-rails_best_practices

---

README.md

Hi,
After I saw https://github.com/reviewdog/errorformat/pull/117, I created the https://github.com/yoheimuta/action-protolint.
I tested this action by https://github.com/yoheimuta/reviewdog-protolint-example.

Add a link to https://github.com/yoheimuta/action-protolint

---

.github/workflows/deploy-doghouse.yml
.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml
go.mod

bump Go 1.19

---

doghouse/service.go

This PR is fix a typo.
- resutls -> results

Fix a typo

---

CHANGELOG.md
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go

This attempts to address https://github.com/reviewdog/action-eslint/issues/62 by calculating the conclusion of a check run based on the level of the annotations.
That is to say:
- if there are any error-level annotations the run is a failure
- if there are any warning- or info-level annotations the run is neutral
- otherwise, the run is a success
For reverse compatibility, the config Level takes precedence when provided.

fix: Calculate check conclusion from annotations

---

CHANGELOG.md
cmd/reviewdog/main.go

Since https://github.com/reviewdog/reviewdog/pull/1170 we can dynamically calculate the check conclusion from annotations if a level config isn't provided. However, reviewdog currently defaults level to error, which prevents the dynamic calculation from ever running.
note: staticcheck/textlint errors are unrelated to changes and occur for other PRs as well (e.g. https://github.com/reviewdog/reviewdog/pull/1425)
todo: I'm going to set up a public test repo to verify that this works as expected

fix: Remove default error level

---

.goreleaser-nightly.yml
.goreleaser.yml

fix DEPRECATED warnings of goreleaser. 
```
Run goreleaser/goreleaser-action@v4
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.14.0/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/9b1579dd-7d1f-4706-b6b1-b183dc0e8cb3 -f /home/runner/work/_temp/7d60f6ed-4281-4a1c-a0c6-03cd59e6d085
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/1.14.0/x64/goreleaser check
• loading config file                              file=.goreleaser.yml
• checking config...
• DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
• DEPRECATED: `archives.replacements` should not be used anymore, check …
```

fix deprecated configure of goreleaser

---

CHANGELOG.md
service/github/githubutils/utils.go
service/github/githubutils/utils_test.go

This PR adds support for a custom github server url via environment variable GITHUB_SERVER_URL. This variable is populated by default in GitHub actions with the current GitHub URL. With this approach we benefit from path link support on self hosted instances of GitHub (GitHub Enterprise), that currently is broken and pointing to `github.com`.
Tell me If you need me to update something. Thanks for the awesome project 💪

feat: add ghe path link support

---

CHANGELOG.md
cienv/github_actions.go

There are several GitHub Actions events that don't include a commit SHA in the event payload fields that are currently parsed by Reviewdog. For example, the [`release` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) only includes a `target_commitish` field that does not contain a commit hash. This renders Reviewdog less suitable for use in workflows triggered by such events.
To improve on the situation, let Reviewdog parse the `GITHUB_SHA` environment variable to fetch a commit SHA if the already available methods fail. [As explained in the GitHub docs](https://docs.github.com/en/actions/learn-github-actions/variables), this environment variable is a useful last resort for other event types.

fix: support determining build info on more GitHub Actions events

---

CHANGELOG.md

update CHANGELOG.md for releasing v0.14.2

---

.goreleaser-nightly.yml
.goreleaser.yml

some properties of `.goreleaser.yml` are now deprecated, and `goreleaser check` fails:
https://github.com/reviewdog/reviewdog/actions/runs/5598907307/jobs/10239188000
```
• loading config file                              file=.goreleaser.yml
• checking config...
• DEPRECATED: `archives.rlcp` should not be used anymore, check https://goreleaser.com/deprecations#archivesrlcp for more info
• DEPRECATED: `brews.tap` should not be used anymore, check https://goreleaser.com/deprecations#brewstap for more info
•                                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
```
I fixed deprecated configures.
> …

Fix goreleaser config

---

comment_iowriter.go
diff/diff.go
diff/parse_test.go
proto/rdf/reviewdog.pb.go
service/bitbucket/annotator.go
service/commentutil/code_fence.go
service/gerrit/change_review.go
service/github/githubutils/utils_test.go
service/gitlab/gitlab_mr_commit.go
service/gitlab/gitlab_mr_discussion.go

apply `go fmt` with Go 1.20

---

.github/workflows/reviewdog.yml
CHANGELOG.md
README.md
cmd/reviewdog/main.go
parser/parser.go
parser/parser_test.go
parser/sarif.go
parser/sarif_test.go
service/serviceutil/serviceutil.go

This PR makes reviewdog can read [SARIF 2.1.0](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html) format.
---
- related: #1175

Add SARIF format input support.

---

CHANGELOG.md

update CHANGELOG for v0.15.0

---

CHANGELOG.md

fix link for v0.15.0 in CHANGELOG

---

CHANGELOG.md
README.md
service/github/github.go
service/github/github_test.go

closes #1572
Support `--filter-mode=file` in `github-pr-review` by falling back to file comment when outside of diff context.

Support `--filter-mode=file` in `github-pr-review`

---

CHANGELOG.md
service/gitlab/gitlab_mr_diff.go

Why is this change useful?
1. It saves some unnecessary Gitlab API calls if that specific envvar is available ([which should be the case since Gitlab 13.7](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html))
2. It allows overriding the base commit sha from an environment variable which I used as a workaround for https://github.com/reviewdog/reviewdog/issues/1150. (I store the sha of the last successfully scanned commit in a file and persist it in the Gitlab CI cache between consecutive job runs. By providing this last scanned SHA as the base commit (`CI_MERGE_REQUEST_DIFF_BASE_SHA` envvar) when running reviewdog, it will only comment for lines which were changed since the last run and will not create multiple comments for issues already existing.

Use CI_MERGE_REQUEST_DIFF_BASE_SHA Gitlab envvar if available

---

cmd/reviewdog/main.go
service/gitlab/gitlab_mr_commit.go
service/gitlab/gitlab_mr_discussion.go
service/gitlab/gitlab_mr_discussion_test.go

[gitlab.Int](https://pkg.go.dev/github.com/xanzy/go-gitlab@v0.94.0#Int) and [gitlab.String](https://pkg.go.dev/github.com/xanzy/go-gitlab@v0.94.0#String) are now deprecated.

migrate deprecated gitlab functions

---

CHANGELOG.md
README.md
cmd/reviewdog/main.go
go.mod
go.sum
service/gitea/gitea.go

Fixes #1295
Should probably wait for [gitea/go-sdk#638](https://gitea.com/gitea/go-sdk/pulls/638)

Add support to report results to Gitea review comments

---

CHANGELOG.md

prepare for releasing v0.16.0

---

CHANGELOG.md
README.md
cmd/reviewdog/doghouse.go
cmd/reviewdog/doghouse_test.go
cmd/reviewdog/main.go
doghouse/appengine/checker.go
doghouse/client/client.go
doghouse/client/client_test.go
doghouse/client/github_client.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
project/run_test.go

This PR adds a new `github-pr-annotations` reporter which bypasses the checks API and uses the existing GitHub annotations fallback to report failures.
It _should_ resolve #403 and allow people to attach annotations in the same check that runs reviewdog.
I've updated all existing tests so that they pass again. I tried to add a test for the GH Actions annotation format specifically, but `core.Error` in `go-actions-toolkit` is hardcoded to write to `os.stdout` which means I can't capture the output to write assertions

Explicit annotation reporter

---

.github/workflows/reviewdog.yml

golangci-lint workflow sometimes fails with timeout error: https://github.com/reviewdog/reviewdog/actions/runs/7627118782/job/20775054992?pr=1649
```
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
Error: Error: golangci-lint exited with status code: 4
```
This pull request will fix it.

extend golangci-lint timeout

---

.github/workflows/deploy-doghouse.yml
doghouse/appengine/app.yaml
go.mod

Go 1.21 is now [generally available](https://cloud.google.com/products/#product-launch-stages) on App Engine.
https://cloud.google.com/appengine/docs/standard/go/release-notes#September_14_2023

doghouse: bump Go 1.21

---

CHANGELOG.md
parser/sarif.go
parser/sarif_test.go

---
This PR supports SARIF file from Trivy.
Trivy SARIF sample
https://github.com/aquasecurity/trivy-sarif-demo/blob/d1968305c1133a0efd42bde85cd3bbefa68aa960/debug-trivy-results.sarif
SARIF v2.1.0 3.29.4 region property
https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541120
SARIF may not have a region property. This PR fixes reviewdog can parse SARIF with no region properties.

fix: SARIF parser: parse with no region result. fix originalOutput field

---

.github/workflows/deploy-doghouse.yml
doghouse/appengine/app.yaml
doghouse/server/doghouse.go
go.mod
service/github/github.go

From Go 1.21, built-in function `min` and `max` are available.
This pull request includes the changes of https://github.com/reviewdog/reviewdog/pull/1647

Use builtin min and max

---

.github/workflows/deploy-doghouse.yml
cmd/reviewdog/main.go
doghouse/appengine/app.yaml
go.mod

Starting from Go 1.21, log/slog is available as a standard library. I think it's a very good option for starting with structured logging.

Introduce slog

---

CHANGELOG.md
service/bitbucket/server_api_helper.go

Fixed sending wrong line number to Bitbucket Server Code Insight Reports (fixes #1652)

Fix sending wrong line number to Bitbucket Server Code Insight Reports

---

.github/workflows/reviewdog.yml

goalngci-lint fail infrequently with --enable-all.
We actually do not need to run all linters.
The original reason I used --enabled-all is just for illustration
purpose.
It might be better to configure our own golangci-lint, but for now let's
use default linters.

CI: stop using golangci-lint --enable-all

---

CHANGELOG.md

Bump version to v0.17.2: Update errorformat version: fix go vet issue #933

---

doghouse/server/storage/installation.go
doghouse/server/storage/token.go

- It's not a notable change.
Hi, I found closers that aren't closed in doghouse. Since it's minor fix, feel free to ignore this.
Go Doc comment on `datastore.NewClient` says:
```go
// Call (*Client).Close() when done with the client.
```
Implementation of `(*Client).Close()` looks to close connection pooling.
```go
// Close closes the Client. Call Close to clean up resources when done with the
// Client.
func (c *Client) Close() error {
return c.connPool.Close()
}
```
So it looks better to be closed.
Adding context, I'm not familiar doghouse at all (though I'm interested in reviewdog). Even I don't know how to run doghouse (https://github.com/reviewdog/reviewdog/issues/1194). I'm developing a static code analyzer and randomly scanning open projects to find practical false positives so …

close datastore.Client

---

.goreleaser.yml

- it's not notable changes.
https://github.com/reviewdog/reviewdog/actions/runs/8662593699/job/23754853000
```
• DEPRECATED: brews.folder should not be used anymore, check https://goreleaser.com/deprecations#brewsfolder for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.25.1/x64/goreleaser' failed with exit code 2
```
https://goreleaser.com/deprecations/#brewsfolder
I change `brews.folder` to `brews.directory` in `.goreleaser.yml` because `brews.folder` was renamed in goreleaser v1.25.

Fix: change brews.folder to brews.directory

---

.github/workflows/release.yml

- it's not notable changes.
https://github.com/reviewdog/reviewdog/actions/runs/8688102935/job/23822999680
```
• DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
```
https://goreleaser.com/deprecations/#-rm-dist
`--rm-dist` has been deprecated in favor of `--clean` in goreleaser v1.15.0.
Therefore, I change `--rm-dist` to `--clean`.

ci: change --rm-dist to --clean

---

parser/rdjson.go
parser/rdjson_test.go
parser/rdjsonl.go
parser/rdjsonl_test.go

Old reviewdog binaries should succeed in parseing given rdjson/rdjsonl
correctly when RDFormat is updated and new fields are added.

rdf: Discard unknown fields when unmarshalling JSON data

---

README.md

I want to add `action-regal` to the README.md

Update README.md to add action-regal

---

service/github/github.go

https://github.com/reviewdog/reviewdog/blob/8aa60fd609d4c2c28fe28511037536535a1c70aa/service/github/github.go#L250-L255
The above code is common regardless of the branch of the if statement.
Therefore, I refactor it so that it is written only once.
- It's not notable changes.

githubCommentLineRange: a same process is written only once

---

CHANGELOG.md
cmd/reviewdog/main.go
cmd/reviewdog/main_test.go
comment_iowriter.go
comment_iowriter_test.go

It reports output to stdout in rdjson/rdjsonl format.
It also changes the default behavior of -filter-mode and -diff command
behavior for local (local/rdjson/rdjsonl) reporters.
If -filter-mode is not provided (-filter-mode=default) and -diff flag is
not provided, reviewdog automatically set -filter-mode=nofilter.

Implement rdjson and rdjsonl reporters

---

.circleci/config.yml

- It's not notable changes.
I update CircleCI's golang image to 1.21.7 and switch from `circleci/golang` image to `cimg/go` image: https://circleci.com/developer/en/images/image/cimg/go
In addition, we have also changed to using an `executor`: https://circleci.com/docs/en/configuration-reference/#executors

Update CircleCI's golang image to 1.21.7

---

scripts/trigger-depup/main.go

- it's not notable changes.
https://github.com/reviewdog/reviewdog/actions/runs/9927782041/job/27423172020
```
POST https://api.github.com/repos/reviewdog/action-eclint/dispatches: 404 Not Found []
exit status 1
```
https://github.com/reviewdog/action-eclint is arcived.
Therefore, CI `release` can't call CI `depup` in this repository.
For this reason, I exclude archived repositories from the targets of the API call.

trigger-depup: Exclude archived repositories

---

CHANGELOG.md
comment_iowriter.go
comment_iowriter_test.go

It's used internally and we shouldn't expose it as output.

Remove original_output from RDJSON(L) output

---

CHANGELOG.md
README.md
cmd/reviewdog/main.go
fail_level.go
fail_level_test.go
project/run.go
project/run_test.go
reviewdog.go
reviewdog_test.go

Now reviewdog can control exit code based on issue severity.
For example, if `-fail-level=warning`, then reviewdog will exit with 0
for issues with info severity, while it will exit with 1 if it finds issues with
error, warning, or unknown severity.
This change also fixes the feature parity with github-[pr-]check reporter.
Previously, only this reporter didn't fail on warning or info level issues (#1846),
and this behavior was removed during refactoring (#1846).
Now users can use `-reporter=github-check -fail-level=error` to restore
the previous behavior.

introduce -fail-level flag and deprecate -fail-on-error

---

.github/workflows/release.yml
.github/workflows/release_test.yml

- it's not notable changes.
I want to run `goreleaser check` in PR if there is a difference in `.goreleaser.yml` or `.goreleaser-nightly.yml`.
Therefore, I separate `goreleaser check` from CI `release`.

Add CI release test

---

.goreleaser-nightly.yml
.goreleaser.yml

-  it's not notable changes.
https://github.com/reviewdog/reviewdog/actions/runs/10369567243/job/28705575699
```
• only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
```
To solve the above problem, I set `version: 2` for `.goreleaser.yml` and `.goreleaser-nightly.yml`.

Set version: 2 for .goreleaser.yml

---

.github/workflows/release.yml
.github/workflows/release_test.yml
.goreleaser-nightly.yml
.goreleaser.yml

release test workflow fails with the latest goreleaser (v2.2.0):
https://github.com/reviewdog/reviewdog/actions/runs/10547764675
this pull request fixes this.

fix: releasing workflow

---

CHANGELOG.md

Update the release dates in the changelog based on the date (UTC timezone) the git tags for the versions were created.

Fix v0.20.2 and v0.20.1 changelog dates

---

scripts/trigger-depup/go.mod

- It's not notable changes.
I add a `toolchain` statement to `scripts/trigger-depup/go.mod`.

Add toolchain in scripts/trigger-depup/go.mod

---

CHANGELOG.md
README.md
cmd/reviewdog/main.go

Reviewdog currently does not report anything for `github-[pr-][check|annotate]` reporters when triggered by pushing a commit.
Previously, diffs were not filtered when running reviewdog with `github-[pr-][check|annotate]` reporters on a non-PR (e.g. push commit).
https://github.com/reviewdog/reviewdog/blob/1cf12d8c1dbae779542917bbe53945bd510f4f9c/doghouse/server/doghouse.go#L61-L65
This makes sense because when not executed on a PR, the `DiffService` is empty.
https://github.com/reviewdog/reviewdog/blob/7e8096c17b1d9080dd25cc4c616ce690361920de/cmd/reviewdog/main.go#L665-L675
However, https://github.com/reviewdog/reviewdog/commit/5e276abc654a39bc0967cfa06c2de821c1c065b8 changed the behaviour of reviewdog to *always* filter the diffs.
Restore the previous behaviour by setting `opt.filterMode …

github-[pr-][check|annotate]: Do not filter if no PR

---

cmd/reviewdog/main.go

Since err != nil has been judged before, nil is returned directly here, which is more obvious, readable and less error-prone.

refactor: return nil when error has already been checked

---

.github/workflows/release.yml
.github/workflows/reviewdog.yml
README.md

This reverts commit bb8647eb65405d610749c5b4e9b46ba6f0532443.
`#default-branch` doesn't work we expected.
see https://github.com/reviewdog/reviewdog/pull/952#pullrequestreview-666216039

Revert "Use $default-branch instead of master"

---

CHANGELOG.md
service/github/diff.go

Previously, if you tried to fallback to Git based fetching with a private repo fork on GitHub Actions, the command would fail because the automatic token used for GitHub Actions is only scoped to the current repo, not the head repo.
```
reviewdog: fail to get diff: failed to run git fetch: remote: Repository not found.
fatal: repository 'https://github.com/wlynch/my-private-fork/' not found
```
GitHub forks store all commit data in the same namespace, which allows you to access commit content from PRs / forks from the base repo. This should allow the use of the default GitHub token to fetch the head PR content.

service/github: Fetch diff from base pull request repo

---

.github/workflows/reviewdog.yml

The job is failing with master branch because it output too many annotations and reaches github action limit.

fix too many annotations
