reviewdog/reviewdog

cmd/watchdogs/main.go

This reverts commit e7ffd8373dd9c05bced5a91dff4e9d7446c2146a.
ref #14

Revert "revert: test"

---

.travis.yml
reviewdog.go

CI: introduce codecov

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go
project/run.go
project/run_test.go

ProjectConf: introduce project based run

---

project/run.go
project/run_test.go

ProjectConf: hide secret environment variables from command executions

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go

ProjectConf: remove 'isatty' because isatty==false in CI server

---

diff.go
diff_test.go

ProjectConf: fix data race of DiffCmd

---

README.md

Document for Project Configuration Based Run

---

github.go
github_test.go
lock.json

Switch to use go-github review API implementation

---

lock.json
manifest.json

ensure `dep ensure -update` works

dep: specify "branch": "v2" for gopkg.in/yaml.v2

---

cmd/reviewdog/main.go
comment.go
comment_iowriter.go
comment_iowriter_test.go
comment_test.go
diff.go
diff_test.go
github.go
github_test.go
lock.json
project/run.go
project/run_test.go
reviewdog.go
reviewdog_test.go

Also, update go-github
Fixes: #80

Support context.Context

---

README.md

Also, mention https://github.com/azu/textlint-reviewdog-example

fix CI configuration example

---

README.md

add how to use reviewdog with Jenkins ghprb plugin

---

Gopkg.lock
github.go
github_test.go

https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review
Fixes #101

Specify commit id to the GitHub review comment request

---

github.go
github_test.go

GitHub now returns diff which take cares renames of files like `git diff
--find-renames`.
We can now use the diff provided by GitHub instead of executing "git
diff" locally, which sometimes introducd a problem (#66)
Tested on #104
https://patch-diff.githubusercontent.com/raw/haya14busa/reviewdog/pull/104.diff
API Reference: https://developer.github.com/v3/pulls/comments/#create-a-comment
Fixed #66 #103
Closes #104

Get diff from GitHub using application/vnd.github.v3.diff media type

---

project/run.go
reviewdog.go

It also reduce needless API call to get diff.

Refactoring project/

---

doghouse/service.go

doghouse: add CheckRequest service request & response

---

.travis.yml

CI: remove coverall

---

cmd/reviewdog/main.go
github.go
gitlab_mr_commit.go
gitlab_mr_discussion.go
gitlab_mr_discussion_test.go
service_base.go

gitlab: support GitLab merge request discussions

---

cienv/cienv.go

It is not directly related to this PR, I also noticed that there is a typo in your project description.
`s/programing/programming/`
> 🐶 Automated code review tool integrated with any code analysis tools regardless programing language

Fix condition to validate repo CI envronment variable

---

README.md

Looking for support by opencollective to sustain reviewdog app server and maintain this project.
https://opencollective.com/reviewdog

Looking for support by opencollective

---

doghouse/server/cookieman/cookieman.go
doghouse/server/cookieman/cookieman_test.go

doghouse/server/cookieman: add cookie manager

---

.gitlab-ci.yml
README.md

Fix typo in .gitlab-ci.yml

---

.travis.yml

Fix coverage test

---

.circleci/config.yml

https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag

Fix release on tag push

---

.github/renovate.json

https://docs.renovatebot.com/presets-default/#preservesemverranges
Fix #253

Use :preserveSemverRanges for renovate bot

---

README.md

Thanks to GoReleaser! https://github.com/goreleaser/goreleaser

linuxbrew is also supported

---

doghouse/server/github.go
doghouse/server/storage/installation.go

See https://github.com/reviewdog/reviewdog/issues/266#issuecomment-533783563 for the errors.

Fix go112 migration errors

---

.circleci/config.yml

I don't remember why I added it...

circleci: do not use || true for golint

---

README.md

https://github.com/reviewdog/action-vint

Add reviewdog/action-vint

---

README.md

https://github.com/reviewdog/action-eslint

Add reviewdog/action-eslint

---

.github/workflows/reviewdog.yml

https://github.com/reviewdog/action-shellcheck

Introduce reviewdog/action-shellcheck

---

README.md

I also added a link to the issue as an example of creating reviewdog GitHub Actions.
Is it ok @Vlaaaaaaad ?

Add reviewdog/action-tflint

---

doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/server/github_checker.go

Support more than 50 annotations

---

doghouse/server/doghouse.go
doghouse/server/doghouse_test.go

github-pr-check: fix missing name

---

README.md

- tsuyoshicho/action-textlint
- tsuyoshicho/action-vimlint

Add tsuyoshicho's actions

---

cienv/github_actions.go
cmd/reviewdog/doghouse.go
go.mod
go.sum
reviewdog.go

github-pr-check: Use logging commands of GitHub Actions as Graceful egradation for Pull Request from forked repository
- https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-error-message-error
- https://github.com/haya14busa/go-actions-toolkit
Ref #411

github-pr-check: Use logging commands of GitHub Actions as Graceful degradation for Pull Request from forked repository

---

.github/workflows/reviewdog.yml
cmd/reviewdog/doghouse.go
cmd/reviewdog/main.go
reviewdog.go
service/github/githubutils/comment_writer.go

- https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-error-message-error
Ref #411

github-pr-review: Use logging commands of GitHub Actions as Graceful degradation for Pull Request from forked repository

---

.github/workflows/reviewdog.yml
README.md

- Graceful Degradataion for Pull Requests from forked repositories

doc: Update Readme for next release

---

README.md

https://github.com/mgrachev/action-dotenv-linter

Add action-dotenv-linter

---

cmd/reviewdog/main.go
doghouse/appengine/github.go
doghouse/appengine/github_webhook.go
doghouse/client/github_client.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/server/github.go
doghouse/server/github_checker.go
go.mod
service/github/github.go
service/github/github_test.go

Fix https://github.com/reviewdog/reviewdog/pull/426

Update go-github from v28 to v29

---

README.md

Following https://github.com/reviewdog/reviewdog/issues/402

chore(docs): add reviewdog/yamllint action

---

README.md

https://somsubhra.com/github-release-stats/?username=reviewdog&repository=reviewdog

Link github release stats

---

README.md

Link: https://github.com/reviewdog/action-brakeman

Add action-brakeman

---

README.md

https://github.com/reviewdog/action-template

Mention action-template in README for creating reviewdog actions

---

README.md

https://github.com/ScaCap/action-ktlint

Add action-ktlint

---

.github/workflows/reviewdog.yml
README.md

https://github.com/reviewdog/action-languagetool

ci: introduce reviewdog/action-languagetool

---

README.md

Add action-fasterer to list of actions in readme.
https://github.com/vk26/action-fasterer

Add action-fasterer to list

---

README.md

improve README about REVIEWDOG_TOKEN

---

.github/workflows/reviewdog.yml
README.md
_testdata/golint.go
cmd/reviewdog/doghouse.go
cmd/reviewdog/doghouse_test.go
difffilter/filter.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/service.go

Exit 1 if conclusion is failure and -fail-on-error for github-check reporter

---

.github/renovate.json

- Enable gomodTidy option
- Enable automerge
- Introduced https://github.com/apps/renovate-approve as well
document: https://docs.renovatebot.com/configuration-options/

renovate: udpate renovate setting

---

cmd/reviewdog/main.go
difffilter/filter.go
difffilter/filter_test.go

Change default filter mode and return error for unknown flag value

---

cmd/reviewdog/main.go
cmd/reviewdog/main_test.go
diff.go

Support empty -diff flag for -repoter=local with -filter-mode=nofilter

---

.github/workflows/reviewdog.yml
cmd/reviewdog/doghouse.go
cmd/reviewdog/doghouse_test.go
cmd/reviewdog/main.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/service.go

github-check reporter: Deprecate OutsideDiff flag and use filter-mode=nofilter instead

---

.github/workflows/go.yml
.travis.yml

Introduce codecov/codecov-action

---

.github/renovate.json

To filter renovate Pull Requests easier.

add "renovate" label for renovate pull requests

---

README.md

Introduce reviewdog nightly release

---

.circleci/config.yml
.github/workflows/release.yml
README.md

You can release new version by merging Pull Requests with specific labels
(bump:major,bump:minor,bump:patch) [1]. You can also push new tag manually
as well.
[1] https://github.com/haya14busa/action-bumpr
ref: #560

Improve release workflow

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

doc: write release process

---

.github/workflows/reviewdog.yml
CHANGELOG.md
_testdata/golint.go
_testdata/reviewdog_error.yml
cmd/reviewdog/doghouse.go
project/run.go
resultmap.go

Fix #596
This is follow-up of #513.

Check unexpected failures for github-check (doghouse) flow

---

doghouse/appengine/app.yaml

doghouse: Update automatic_scaling config to reduce the instance cost

---

doghouse/appengine/checker.go
doghouse/appengine/main.go
go.mod
go.sum

https://cloud.google.com/trace/docs/setup/go

doghouse: Support trace

---

README.md

Added Android Lint action
Closes #625

Added Android Lint action

---

.github/workflows/codeql-analysis.yml

https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code

Enable Code Scanning

---

linters/go.mod
linters/go.sum

Update module kisielk/errcheck to v1.3.0

---

.github/renovate.json
.goreleaser.yml

https://docs.renovatebot.com/semantic-commits/

Always use chore(deps) prefix for renovate PRs

---

.github/workflows/reviewdog.yml
README.md

Introduce reviewdog/action-alex@v1

---

cmd/reviewdog/main.go
doghouse/appengine/github.go
doghouse/appengine/github_webhook.go
doghouse/client/github_client.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/server/github.go
doghouse/server/github_checker.go
go.mod
go.sum
service/github/github.go
service/github/github_test.go

It supports multiline review comments.

Update go-github to v32

---

cmd/reviewdog/doghouse.go
cmd/reviewdog/doghouse_test.go
comment_iowriter.go
comment_iowriter_test.go
doghouse/server/doghouse.go
doghouse/service.go
filter.go
filter_test.go
parser.go
reviewdog.go
reviewdog_test.go
service/commentutil/commentutil.go
service/gerrit/change_review.go
service/gerrit/change_review_test.go
service/github/github.go
service/github/github_test.go
service/github/githubutils/comment_writer.go
service/github/githubutils/utils.go
service/github/githubutils/utils_test.go
service/gitlab/gitlab_mr_commit.go
service/gitlab/gitlab_mr_commit_test.go
service/gitlab/gitlab_mr_discussion.go
service/gitlab/gitlab_mr_discussion_test.go

Use Reviewdog Diagnostic Format internally

---

doghouse/appengine/app.yaml

doghouse: use Go 1.14

---

.github/workflows/reviewdog.yml
_testdata/custom.txt
_testdata/custom_rdjsonl.json
cmd/reviewdog/doghouse.go
cmd/reviewdog/doghouse_test.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/service.go

Support annotation level per result and range annotation.

github-check: Support Reviewdog Diagnostic Format

---

cmd/reviewdog/doghouse.go
cmd/reviewdog/main.go
doghouse/appengine/github.go
doghouse/client/client.go
doghouse/server/doghouse.go
doghouse/server/github.go
project/run.go
reviewdog.go
service/gerrit/change_diff.go
service/gerrit/change_review.go
service/github/github.go
service/gitlab/gitlab_mr_commit.go
service/gitlab/gitlab_mr_diff.go
service/gitlab/gitlab_mr_discussion.go
service/serviceutil/serviceutil.go

Used https://github.com/fatih/errwrap

wrap errors with %w directive

---

cmd/reviewdog/main.go
parser/checkstyle.go
parser/checkstyle_test.go
parser/errorformat.go
parser/errorformat_test.go
parser/parser.go
parser/parser_test.go
parser/rdjsonl.go
parser/rdjsonl_test.go
project/run.go
reviewdog.go
reviewdog_test.go

refactor: create parser package

---

doghouse/server/github_checker.go

doghouse: sleep 1 sec before retrying

---

.circleci/config.yml
.github/workflows/go.yml
.github/workflows/reviewdog.yml
.travis.yml
README.md

Minor update of CI config

---

parser/checkstyle.go
parser/checkstyle_test.go
parser/errorformat.go
parser/errorformat_test.go
parser/parser.go

parser: Improve RD Format support

---

service/github/githubutils/comment_writer.go

github-action-log: support severity level

---

.gitlab-ci.yml
CHANGELOG.md
_testdata/custom.txt
_testdata/custom_rdjsonl.json
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
service/commentutil/commentutil.go
service/commentutil/commentutil_test.go
service/github/github.go
service/github/github_test.go
service/gitlab/gitlab_mr_commit.go
service/gitlab/gitlab_mr_commit_test.go
service/gitlab/gitlab_mr_discussion.go
service/gitlab/gitlab_mr_discussion_test.go

service/commentutil: Improve support of rdformat

---

cmd/reviewdog/main.go

remove deprecated -ci flag

---

.github/workflows/release.yml
CHANGELOG.md

Cherry pick https://github.com/reviewdog/reviewdog/pull/709

Release v0.10.2

---

scripts/trigger-depup/main.go

scripts/trigger-depup: run flag.Parse()

---

.github/CONTRIBUTING.md

doc: add Hot Fix Release process

---

.github/workflows/reviewdog.yml
CHANGELOG.md
README.md

https://github.com/reviewdog/action-setup

introduce reviewdog/action-setup

---

README.md

Add action-ansiblelint

---

README.md

Fixes: https://github.com/reviewdog/reviewdog/issues/496

Add documentation for tee debugging flag

---

cmd/reviewdog/main.go

Remove duplicate lines.

---

cmd/reviewdog/main.go
doghouse/appengine/checker.go
doghouse/appengine/github.go
doghouse/appengine/main.go
doghouse/appengine/warmup.go
doghouse/client/client.go
filter/diff_filter.go
filter/filter.go
filter/filter_test.go
go.mod
parser/diff.go
parser/errorformat.go
parser/parser.go
parser/rdjson.go
parser/rdjsonl.go
reviewdog_test.go
service/gerrit/change_review.go
service/gerrit/change_review_test.go
service/github/github.go
service/github/githubutils/comment_writer.go
service/gitlab/gitlab_mr_commit.go
service/gitlab/gitlab_mr_diff.go
service/gitlab/gitlab_mr_discussion.go

Some fixes.

---

service/github/github.go
service/github/github_test.go

github-pr-review: [suggestion] support start only location with ranged suggestion

---

_testdata/custom.txt
_testdata/custom_rdjson.json
filter/diff_filter.go
filter/filter.go
filter/filter_test.go
service/github/github.go
service/github/github_test.go

github-pr-review: Prefer suggestion range to diagnostic range as GitHub comment range

---

CHANGELOG.md
README.md
cmd/reviewdog/main.go

Update document about RDFormat and Code Suggestions

---

.circleci/config.yml

Fix doghouse deploy config

---

README.md

External product, do no need update CHANGELOG.
---
Add new GitHub Action - action-mypy

feat: add mypy action

---

scripts/trigger-depup/main.go

scripts/trigger-depup: increase per-page size to 100

---

README.md

doc: add description about `format` key in config file

---

go.mod
go.sum
scripts/trigger-depup/go.mod
scripts/trigger-depup/go.sum

fixes https://github.com/reviewdog/reviewdog/pull/936

bump go-github v35.2.0

---

.github/workflows/reviewdog.yml
.travis.yml

Reduce Builds On Travis

---

README.md

This adds a link to the README for the action I just put together to run pyright

Add link to action-pyright

---

proto/rdf/README.md

Fix typo in rdjson format example

---

CHANGELOG.md

bump v0.12.0

---

.github/workflows/release.yml
.goreleaser.yml

https://goreleaser.com/deprecations/#brewsgithub

fix deprecated brews.github config of goreleaser

---

CHANGELOG.md

update CHANGELOG for v0.13.0

---

README.md

Adding Python Pylint action to Readme.md

---

service/gitlab/gitlab_mr_discussion.go
service/gitlab/gitlab_mr_discussion_test.go

Follow #678, this pull request allow use Gitlab suggestions in merge request discussion
Most of code in this PR come from #842 but the author @caseycs is inactive for a long time, I create a new one.
Please take a look @haya14busa

Use Gitlab suggestions in merge request comments

---

README.md

Update star chart link

---

.circleci/config.yml
.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml
.travis.yml
go.mod
scripts/trigger-depup/go.mod

Go 1.17 is released

---

CHANGELOG.md
doghouse/service.go

I fixed DEPRECATED to Deprecated.
FYI
https://github.com/golang/go/wiki/Deprecated

Fix deprecate letter case

---

doghouse/appengine/checker.go

for avoiding reflected cross-site scripting vulnerability.
and it also fixes Code scanning alerts about [CWE-117](https://cwe.mitre.org/data/definitions/117.html).

set Content-Type header explicitly

---

README.md

I just made a GitHub Action to invoke `erb-lint`.

doc: Add a link to tk0miya/action-erblint action

---

README.md

Add markdownlint to the list of public reviewdog actions

---

doghouse/server/doghouse.go
doghouse/server/doghouse_test.go

Enforce size limit for check-run summary

---

README.md

some URLs return 301 responses, so I replaced them with their corresponding redirect destinations.

fix textlint warnings

---

.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml
go.mod

bump Go 1.20

---

README.md

doc: Add a link to tk0miya/action-steep action

---

.github/workflows/deploy-doghouse.yml
doghouse/appengine/app.yaml

bump Go 1.20 of doghouse server

---

package-lock.json
package.json

fix:  Error: Could not find formatter @microsoft/eslint-formatter-sarif
https://github.com/reviewdog/reviewdog/actions/runs/6105066286/job/16567999766
```
Run npx textlint -f @microsoft/eslint-formatter-sarif README.md | \
Error
Could not find formatter @microsoft/eslint-formatter-sarif
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
Stack trace
Error: Could not find formatter @microsoft/eslint-formatter-sarif
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
at loadFormatter (/home/runner/work/reviewdog/reviewdog/node_modules/@textlint/linter-formatter/lib/src/index.js:55:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async …
```

install @microsoft/eslint-formatter-sarif

---

cienv/cienv.go
cienv/cienv_test.go

https://woodpecker-ci.org/docs/next/usage/environment

Improve compatibility with Woodpecker CI

---

README.md

I created GitHub Actions for Biome.
I add this action's link at README.md.
- I think this change is not notable change.

New GihuHub Action: Biome

---

CHANGELOG.md

@shogo82148 I missed the invitation to the org and didn't accept in time. Could you please label this PR with `minor` to trigger a release?

Update Changelog for 0.17.0 release

---

service/bitbucket/cloud_api_client.go

chore: remove repetitive word

---

cmd/reviewdog/doghouse.go
filter/diff_filter.go
filter/filter.go
filter/filter_test.go
parser/diff.go
pathutil/pathutil.go

refactor: create pathutil package

---

go.mod
go.sum
parser/sarif.go
parser/sarif_test.go

- Use github.com/haya14busa/go-sarif for sarif struct
- Support related locations with the SARIF parser

Support Sarif related locations

---

README.md

Update the used-by badge

---

.github/workflows/reviewdog.yml
CHANGELOG.md
cmd/reviewdog/main.go
comment_iowriter.go
comment_iowriter_test.go

Support -reporter=sarif

---

.github/workflows/reviewdog.yml

https://github.com/github/codeql-action/issues/2117

Add actions: read permission to upload sarif action

---

.github/workflows/reviewdog.yml

Add security-events: write for upload-sarif action

---

.github/workflows/deploy-doghouse.yml

Fix deploy doghouse code

---

.github/workflows/depup.yml

fix depup config

---

.github/workflows/depup.yml

Add workflow_dispatch to depup workflow

---

.github/workflows/reviewdog.yml
CHANGELOG.md
_testdata/custom.txt
_testdata/custom_rdjson.json
cmd/reviewdog/main.go
doghouse/appengine/github.go
doghouse/appengine/github_webhook.go
doghouse/server/doghouse.go
doghouse/server/doghouse_test.go
doghouse/server/github.go
go.mod
go.sum
scripts/trigger-depup/main.go
service/github/check.go
service/github/check_test.go
service/github/diff.go
service/github/diff_test.go
service/github/github.go
service/github/github_test.go

Support posting comments outside diff context in github-pr-review reporter

---

CHANGELOG.md

https://github.com/reviewdog/reviewdog/issues/1829
I add v0.20.0 to CHANGELOG.md.

CHANGELOG: Add v0.20.0

---

CHANGELOG.md
service/github/check.go

Fix filtering with github-[pr-]check reporter

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yml
.github/workflows/rdformat.yml

I only activate the `pull_request` trigger in PR because this trigger and the `push` trigger were activated.

Only activate the pull_request trigger in PR

---

CHANGELOG.md
filter/filter.go
pathutil/pathutil.go
pathutil/pathutil_test.go
reviewdog.go

Normalize path in related locations

---

proto/rdf/README.md

fix broken links

---

README.md

Pin reviewdog/action-setup version in README

---

.goreleaser-nightly.yml
.goreleaser.yml
CHANGELOG.md

ref: https://goreleaser.com/blog/reproducible-builds/

use -trimpath flag for reproducible build

---

.github/workflows/reviewdog.yml
.reviewdog.yml

follow up of https://github.com/reviewdog/reviewdog/pull/2260
I fixed wrong job. The error was actually from a job using .reviewdog.yml conf

fix too many annotations error (again)
